# Site settings
title: Chonky Plonki
email: chonkyplonki@gmail.com
url: https://github.com/jeromelachaud/freelancer-theme
description: "Chonky Plonki's website - I make art and games!"
keywords: "ChonkyPlonki, Chonky Plonky, game developer, artist, sculptur, art, games, portfolio"
skills: "Gentle greetings 😊
 <br>
 <br>I love coding, hammering at tech, making games and art 🎀 
 <br> 
 <br>On this website I've collected projects I've done and have been a part of.  
 <br>Feel free to have a look at them in the <a href= 'https://chonkyplonki.github.io/ChonkyPlonki.Website/portfolio/' class='custom-link-pink'>Portfolio</a>. 
 <br>You can also contact me any time, you'll find my contact details in <a href='https://chonkyplonki.github.io/ChonkyPlonki.Website/contact/' class='custom-link-pink'>Contact</a>. 
 <br>
 <br> All the best, hope you have a gentle day! 🐸
 " 
baseurl: "/ChonkyPlonki.Website"
url: "https://chonkyplonki.github.io" # the base hostname & protocol for your site
meta_author: LastName FirstName

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: caeea5 #80B3FF //old: e8b0bb
  primary-rgb: "90,31,93" # old: "128,179,255"
  primary-font-color: 141f06

  secondary: 2b4019 #FD6E8A old: 502c38 
  secondary-dark: 141f06 #A2122F old: 31151e
  secondary-dark-rgb: 18,52,86;
  secondary-dark-rgb-transparent: 18,52,86,0.6;
  seconfary-font-color: ffffff

# Footer settings
footer:
  copyright: Chonky Plonki
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/ChonkyPlonki
  - title: youtube
    url: https://www.youtube.com/@ChonkyPlonki

# Postal address (add as many lines as necessary)
address:
  - line: Scandinavia

# Credits content
credits: 'This website was based on the Freelancer Github Templates. Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      author: "chonkyplonki"

collections:
  portfolioposts:
    output: true






